# Generated by Django 6.0.7 on 2026-08-14 16:46

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_customprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
