# Generated by Django 6.0.7 on 2026-08-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/receipts/'),
        ),
    ]
