# Generated by Django 6.0.7 on 2026-08-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_cart_session_key_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_en',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_fa',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name_fa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
