# Generated by Django 6.0.7 on 2026-08-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_order_status_en_order_status_fa_orderitem_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_fa',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='name_fa',
        ),
    ]
